### ISSUE TITLE
Remove typo in main.py file

### ISSUE THREAD

**Issue by caglakahriman** [kadirgokhann/api42_#8]
There's a small typo in main.py file, line 5. Replace dot with close parenthesis.
<img width="328" alt="Screenshot 2023-02-18 at 22 57 48" src="https://user-images.githubusercontent.com/44096617/219887192-abc0b8b6-b1b8-412d-9a6f-19277d9daf9d.png">

**Comment by kadirgokhann** [comment]
Thank you!
